- name: Run playbook locally
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    user: develop
    spotifyd_version: 0.4.1
    os: linux-aarch64
    spotify_device_name: Rossis Röhren Radio
  
  roles:
    - main
    - spotifyd