---
- name: Ensure venv directory exists
  file:
    path: /home/{{ user }}/{{ folder }}/venv
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Create Python virtual environment
  command: python3 -m venv /home/{{ user }}/{{ folder }}/venv
  args:
    creates: /home/{{ user }}/{{ folder }}/venv/bin/activate

- name: Install gpiod in venv
  pip:
    name: gpiod
    virtualenv: /home/{{ user }}/{{ folder }}/venv

- name: Copy Python script
  copy:
    src: "{{ playbook_dir }}/../app/main.py"
    dest: /home/{{ user }}/{{ folder }}/main.py
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  notify: Restart rossis_roehren_radio service

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/rossis_roehren_radio.service
    content: |
      [Unit]
      Description=Rossis Roehren Radio Script
      After=network.target

      [Service]
      ExecStart=/home/{{ user }}/{{ folder }}/venv/bin/python /home/{{ user }}/{{ folder }}/main.py
      WorkingDirectory=/home/{{ user }}/{{ folder }}
      StandardOutput=journal
      StandardError=journal
      Restart=always
      User={{ user }}

      [Install]
      WantedBy=multi-user.target
  notify: Restart rossis_roehren_radio service
