---
- name: Ensure venv directory exists
  file:
    path: /home/{{ user }}/{{ folder }}/venv
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Create Python virtual environment
  command: python3 -m venv /home/{{ user }}/{{ folder }}/venv
  args:
    creates: /home/{{ user }}/{{ folder }}/venv/bin/activate

- name: Install smbus2 in venv
  pip:
    name: smbus2
    virtualenv: /home/{{ user }}/{{ folder }}/venv

- name: Install gpiod in venv
  pip:
    name: gpiod
    virtualenv: /home/{{ user }}/{{ folder }}/venv

- name: Ensure src directory exists for scripts
  file:
    path: /home/{{ user }}/{{ folder }}/src
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Copy Python scripts
  copy:
    src: "{{ playbook_dir }}/../app/src/"
    dest: /home/{{ user }}/{{ folder }}/src/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  notify: Restart rossis_roehren_radio service

- name: Create systemd service file
  copy:
    dest: /etc/systemd/system/rossis_roehren_radio.service
    content: |
      [Unit]
      Description=Rossis Roehren Radio Script
      After=sound.target

      [Service]
      Environment="XDG_RUNTIME_DIR=/run/user/{{ user_id }}" 
      ExecStart=/home/{{ user }}/{{ folder }}/venv/bin/python /home/{{ user }}/{{ folder }}/src/main.py
      WorkingDirectory=/home/{{ user }}/{{ folder }}
      StandardOutput=journal
      StandardError=journal
      Restart=always
      RestartSec=5
      User={{ user }}

      [Install]
      WantedBy=multi-user.target
  notify: Restart rossis_roehren_radio service
